"""empty message

Revision ID: 0329a2523d00
Revises: 0ccff5cabe0f
Create Date: 2021-11-02 16:30:11.334757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0329a2523d00'
down_revision = '0ccff5cabe0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('abilities', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('base_experience', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('sprite', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('hp', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('attack', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('defense', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'defense')
    op.drop_column('post', 'attack')
    op.drop_column('post', 'hp')
    op.drop_column('post', 'sprite')
    op.drop_column('post', 'base_experience')
    op.drop_column('post', 'abilities')
    # ### end Alembic commands ###
