"""empty message

Revision ID: 0e4d9d05bcb9
Revises: 93c986eb0146
Create Date: 2021-11-04 16:04:31.591556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4d9d05bcb9'
down_revision = '93c986eb0146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first', sa.String(length=150), nullable=True))
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('user', 'first')
    # ### end Alembic commands ###
