"""empty message

Revision ID: 536d4a20125b
Revises: 685e123cb50e
Create Date: 2021-11-04 16:41:00.561141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536d4a20125b'
down_revision = '685e123cb50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('irst_name', sa.String(length=150), nullable=True))
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('user', 'irst_name')
    # ### end Alembic commands ###
